import AppKit
import CryptoKit
import ImageIO
import UniformTypeIdentifiers

/// Watches the general pasteboard and turns each change into a stored history entry.
///
/// The timer only reads a change counter. Pasteboard contents are touched exclusively when
/// that counter moves, and heavy work such as hashing, thumbnailing and disk writes happens
/// off the main thread.
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int
    /// Highest change counter value produced by Clipline's own writes.
    private var ownWriteChangeCount = -1
    private let processingQueue = DispatchQueue(label: "com.joymadhu.Clipline.capture", qos: .utility)

    /// Pasteboard hints other apps use to mark content that must not be recorded.
    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private init() {
        lastChangeCount = pasteboard.changeCount
        NotificationCenter.default.addObserver(self, selector: #selector(settingsChanged),
                                               name: .clipMonitorSettingsChanged, object: nil)
    }

    func start() {
        restartTimer()
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    @objc private func settingsChanged() {
        restartTimer()
    }

    private func restartTimer() {
        timer?.invalidate()
        timer = nil
        let settings = SettingsStore.shared
        guard !settings.monitoringPaused else { return }
        let interval = settings.detectionSpeed.interval
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        // A generous tolerance lets the system coalesce our wake ups with other timers.
        timer.tolerance = interval * 0.4
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Call right after Clipline itself writes to the pasteboard.
    ///
    /// Reads the counter after the fact rather than predicting it, because a single write
    /// can bump it more than once (clearing and declaring types each count), which used to
    /// let the app record its own paste back into the history.
    func markOwnWrite() {
        ownWriteChangeCount = pasteboard.changeCount
    }

    /// Captures whatever is on the pasteboard right now, whether or not it changed, and hands
    /// back the row it landed in. Used by the pin action, which must know the exact entry.
    func captureNow(completion: @escaping (Int64?) -> Void) {
        capture(force: true, completion: completion)
    }

    private func poll() {
        capture(force: false, completion: nil)
    }

    private func capture(force: Bool, completion: ((Int64?) -> Void)?) {
        let changeCount = pasteboard.changeCount
        if !force {
            guard changeCount != lastChangeCount else { return }
        }
        lastChangeCount = changeCount
        if !force, changeCount <= ownWriteChangeCount {
            completion?(nil)
            return
        }

        let settings = SettingsStore.shared
        guard force || !settings.monitoringPaused else {
            completion?(nil)
            return
        }

        let types = pasteboard.types ?? []
        if settings.ignoreConcealed {
            if types.contains(ClipboardMonitor.concealedType)
                || types.contains(ClipboardMonitor.transientType)
                || types.contains(ClipboardMonitor.autoGeneratedType) {
                completion?(nil)
                return
            }
        }

        let source = NSWorkspace.shared.frontmostApplication
        let sourceBundle = source?.bundleIdentifier ?? ""
        if !sourceBundle.isEmpty, settings.ignoredBundleIDs.contains(sourceBundle) {
            completion?(nil)
            return
        }
        let sourceName = source?.localizedName ?? ""

        // Snapshot the settings we need. They are observable state owned by the main thread.
        let limit = settings.maxItemBytes
        let historyLimit = settings.historyLimit
        let retentionDays = settings.retentionDays

        guard let raw = readRawPasteboard(storeFiles: settings.storeFiles,
                                          storeImages: settings.storeImages,
                                          limit: limit) else {
            completion?(nil)
            return
        }

        // Hashing, image conversion, thumbnailing and disk writes all happen off the main
        // thread. Copying a full screen screenshot must never stall the interface.
        processingQueue.async {
            guard let payload = Self.makePayload(from: raw,
                                                 sourceName: sourceName,
                                                 sourceBundle: sourceBundle,
                                                 limit: limit) else {
                if let completion { DispatchQueue.main.async { completion(nil) } }
                return
            }
            let id = ClipStore.shared.insert(payload,
                                             historyLimit: historyLimit,
                                             retentionDays: retentionDays)
            if let completion { DispatchQueue.main.async { completion(id) } }
        }
    }

    /// What the pasteboard held, read on the main thread and nothing more.
    private enum RawCapture {
        case files([URL])
        case image(Data, isTIFF: Bool)
        case text(String, rtf: Data?)
    }

    private func readRawPasteboard(storeFiles: Bool, storeImages: Bool, limit: Int) -> RawCapture? {
        // Files first: a copied file also carries a string representation we do not want.
        if storeFiles,
           let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                             options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls)
        }

        if storeImages {
            if let data = pasteboard.data(forType: .png), data.count <= limit {
                return .image(data, isTIFF: false)
            }
            if let data = pasteboard.data(forType: .tiff), data.count <= limit {
                return .image(data, isTIFF: true)
            }
        }

        guard let string = pasteboard.string(forType: .string) else { return nil }
        guard !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        guard string.utf8.count <= limit else { return nil }
        let rtf = pasteboard.data(forType: .rtf)
        return .text(string, rtf: (rtf?.count ?? 0) <= limit ? rtf : nil)
    }

    /// Builds the stored payload. Safe to call from any queue.
    private static func makePayload(from raw: RawCapture,
                                    sourceName: String,
                                    sourceBundle: String,
                                    limit: Int) -> CapturedPayload? {
        var payload: CapturedPayload

        switch raw {
        case .files(let urls):
            let paths = urls.map(\.path)
            guard let encoded = try? JSONEncoder().encode(paths) else { return nil }
            let preview = urls.count == 1
                ? urls[0].lastPathComponent
                : urls.map(\.lastPathComponent).joined(separator: ", ")
            payload = CapturedPayload(
                kind: .file,
                hash: digest(kind: .file, data: encoded),
                preview: clip(preview, to: ClipStore.previewLimit),
                searchText: clip(paths.joined(separator: " ").lowercased(), to: ClipStore.searchLimit),
                body: nil,
                blobData: encoded,
                byteSize: encoded.count,
                fileCount: urls.count
            )
            payload.blobExtension = "json"
            // File rows draw a system icon at display time, so no thumbnail is written.

        case .image(let data, let isTIFF):
            // TIFF from screenshots is large, so store it as PNG instead.
            var stored = data
            var fileExtension = "png"
            if isTIFF {
                if let png = convertToPNG(data) {
                    stored = png
                } else {
                    fileExtension = "tiff"
                }
            }
            let size = imageDimensions(stored)
            payload = CapturedPayload(
                kind: .image,
                hash: digest(kind: .image, data: stored),
                preview: "Image",
                searchText: "image screenshot picture",
                body: nil,
                blobData: stored,
                byteSize: stored.count,
                pixelWidth: size.width,
                pixelHeight: size.height
            )
            payload.blobExtension = fileExtension
            payload.thumbData = thumbnail(from: stored, maxPixel: 256)

        case .text(let string, let rtf):
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            var kind = ClipKind.text
            if isLink(trimmed) {
                kind = .link
            } else if trimmed.count <= 32, NSColor.fromClipboardString(trimmed) != nil {
                kind = .color
            }
            payload = CapturedPayload(
                kind: kind,
                hash: digest(kind: kind, data: Data(string.utf8)),
                preview: clip(collapse(string), to: ClipStore.previewLimit),
                searchText: clip(string.lowercased(), to: ClipStore.searchLimit),
                body: string,
                byteSize: string.utf8.count
            )
            payload.rtfData = rtf
        }

        payload.sourceName = sourceName
        payload.sourceBundle = sourceBundle
        return payload
    }

    // MARK: Static helpers

    /// The kind is part of the digest so a path copied as text never folds into the same
    /// entry as that file copied in Finder.
    static func digest(kind: ClipKind, data: Data) -> String {
        var hasher = SHA256()
        hasher.update(data: Data(kind.rawValue.utf8))
        hasher.update(data: data)
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }

    static func clip(_ value: String, to limit: Int) -> String {
        value.count <= limit ? value : String(value.prefix(limit))
    }

    /// Collapses runs of whitespace so list rows stay on one tidy line.
    static func collapse(_ value: String) -> String {
        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.contains(where: { $0 == "\n" || $0 == "\t" || $0 == "\r" }) else { return trimmed }
        return trimmed.split(whereSeparator: { $0.isNewline || $0 == "\t" })
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
            .joined(separator: " ")
    }

    static func isLink(_ value: String) -> Bool {
        guard !value.contains(" "), value.count < 2048 else { return false }
        let lowered = value.lowercased()
        guard lowered.hasPrefix("http://") || lowered.hasPrefix("https://")
                || lowered.hasPrefix("ftp://") || lowered.hasPrefix("mailto:") else { return false }
        return URL(string: value) != nil
    }

    static func imageDimensions(_ data: Data) -> (width: Int, height: Int) {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any] else {
            return (0, 0)
        }
        let width = properties[kCGImagePropertyPixelWidth] as? Int ?? 0
        let height = properties[kCGImagePropertyPixelHeight] as? Int ?? 0
        return (width, height)
    }

    /// Small JPEG preview generated without ever decoding the full sized image.
    static func thumbnail(from data: Data, maxPixel: Int) -> Data? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil) else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxPixel
        ]
        guard let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }
        let output = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(output, UTType.jpeg.identifier as CFString, 1, nil) else { return nil }
        CGImageDestinationAddImage(destination, image, [kCGImageDestinationLossyCompressionQuality: 0.72] as CFDictionary)
        guard CGImageDestinationFinalize(destination) else { return nil }
        return output as Data
    }

    static func convertToPNG(_ data: Data) -> Data? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else { return nil }
        let output = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(output, UTType.png.identifier as CFString, 1, nil) else { return nil }
        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination) else { return nil }
        return output as Data
    }

}

extension NSColor {
    /// Parses hex and rgb notations so colour codes get a swatch in the history.
    static func fromClipboardString(_ value: String) -> NSColor? {
        var text = value.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if text.hasPrefix("#") { text.removeFirst() }
        if text.hasPrefix("0x") { text.removeFirst(2) }

        if text.count == 3 || text.count == 6 || text.count == 8,
           text.allSatisfy({ $0.isHexDigit }) {
            var expanded = text
            if text.count == 3 {
                expanded = text.map { String(repeating: String($0), count: 2) }.joined()
            }
            var value: UInt64 = 0
            guard Scanner(string: expanded).scanHexInt64(&value) else { return nil }
            if expanded.count == 6 {
                return NSColor(srgbRed: CGFloat((value >> 16) & 0xFF) / 255,
                               green: CGFloat((value >> 8) & 0xFF) / 255,
                               blue: CGFloat(value & 0xFF) / 255,
                               alpha: 1)
            }
            return NSColor(srgbRed: CGFloat((value >> 24) & 0xFF) / 255,
                           green: CGFloat((value >> 16) & 0xFF) / 255,
                           blue: CGFloat((value >> 8) & 0xFF) / 255,
                           alpha: CGFloat(value & 0xFF) / 255)
        }

        if text.hasPrefix("rgb"), let open = text.firstIndex(of: "("), let close = text.firstIndex(of: ")") {
            let inner = text[text.index(after: open)..<close]
            let parts = inner.split(whereSeparator: { $0 == "," || $0 == " " || $0 == "/" })
                .compactMap { Double($0.trimmingCharacters(in: .whitespaces)) }
            guard parts.count >= 3 else { return nil }
            let alpha = parts.count > 3 ? parts[3] : 1
            return NSColor(srgbRed: CGFloat(parts[0] / 255), green: CGFloat(parts[1] / 255),
                           blue: CGFloat(parts[2] / 255), alpha: CGFloat(alpha))
        }
        return nil
    }
}
